### ISSUE TITLE
Unable to load any world on Linux

### ISSUE THREAD

**Issue by SiebenCorgie** [PistonDevelopers/hematite#274]
Hi,  

I wanted to try hematite just for fun, but I am unable to start any world with it. I installed version 1.8.8 for Linux, because the program seams to look for it.

*The error is the following:*
`Opening "/home/*USER*/.minecraft/versions/1.8.8/1.8.8.jar"...
File "/home/*USER*/.minecraft/versions/1.8.8/1.8.8.jar" contains 5597 files.
Extracted 3085 files.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

I placed a copy of the world in the hematite folder but that doesn't do anything. 

*The content with RUST_BACKTRACE=1 is:*
`    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/hematite ./New\\\ World/`
Opening "/home/*USER*/.minecraft/versions/1.8.8/1.8.8.jar"...
File "/home/*USER*/.minecraft/versions/1.8.8/1.8.8.jar" contains 5597 files.
Extracted 3085 files.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
stack backtrace:
   1:     0x5604bd82464a - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5604bd82931f - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x5604bd827586 - std::panicking::default_hook::h5897799da33ece67
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x5604bd827c37 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x5604bd827ac4 - std::panicking::begin_panic::hbb38be1379e09df0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x5604bd8279e9 - std::panicking::begin_panic_fmt::h26713cea9bce3ab0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x5604bd827977 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x5604bd864d9d - core::panicking::panic_fmt::hcfbb59eeb7f27f75
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x5604bd623dc4 - core::result::unwrap_failed::h15a0fc826f4081f4
  10:     0x5604bd66d80a - hematite::main::h57298bcaf003982c
  11:     0x5604bd830dfa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  12:     0x5604bd828655 - std::rt::lang_start::hd661476ce2fc2931
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  13:     0x7f178ebe2290 - __libc_start_main
  14:     0x5604bd6200a9 - _start
  15:                0x0 - <unknown>
`

*Notes*
I am on Arch-Linux and I use Rustup with the nightly-build.
If you need more information I'll try to provide them.

-siebencorgie

**Comment by eddyb** [comment]
I edited your comment to use "fence code blocks" which are a bit more readable.

**Comment by SiebenCorgie** [comment]
thanks!

**Comment by mattico** [comment]
Could you provide a backtrace using a debug build? (i.e. no `--release`)

It'll be quite slow but we should be able to see what line it's panicking on then.

**Comment by SiebenCorgie** [comment]
Sure,
This one is with `cargo run "New\ World"`


``cargo run "New\ World" 
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/hematite New\\\ World`
Opening "/home/siebencorgie/.minecraft/versions/1.8.8/1.8.8.jar"...
File "/home/siebencorgie/.minecraft/versions/1.8.8/1.8.8.jar" contains 5597 files.
Extracted 3085 files.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.``

And this one is with `RUST_BACKTRACE=1 `

``RUST_BACKTRACE=1 cargo run "New\ World" 
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/hematite New\\\ World`
Opening "/home/siebencorgie/.minecraft/versions/1.8.8/1.8.8.jar"...
File "/home/siebencorgie/.minecraft/versions/1.8.8/1.8.8.jar" contains 5597 files.
Extracted 3085 files.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
stack backtrace:
   1:     0x55c6781a011a - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55c6781a4f6f - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x55c6781a31d6 - std::panicking::default_hook::h5897799da33ece67
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x55c6781a3887 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x55c6781a3714 - std::panicking::begin_panic::hbb38be1379e09df0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x55c6781a3639 - std::panicking::begin_panic_fmt::h26713cea9bce3ab0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x55c6781a35c7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x55c6781e09ed - core::panicking::panic_fmt::hcfbb59eeb7f27f75
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x55c677a1feae - core::result::unwrap_failed::h15a0fc826f4081f4
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  10:     0x55c677a03255 - <core::result::Result<T, E>>::unwrap::h444a74d7f321bea8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/result.rs:737
  11:     0x55c677ace7e4 - hematite::main::h57298bcaf003982c
                        at /home/siebencorgie/Scripts/Rust/TutorialsNStuff/Piston/hematite/src/main.rs:105
  12:     0x55c6781aca4a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  13:     0x55c6781a42a5 - std::rt::lang_start::hd661476ce2fc2931
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  14:     0x55c677aec202 - main
  15:     0x7f5463b03290 - __libc_start_main
  16:     0x55c6779a43c9 - _start
  17:                0x0 - <unknown>``

**Comment by eddyb** [comment]
@SiebenCorgie For the record, you need three (i.e ```) and they have to be on their own lines.

**Comment by Geemili** [comment]
@SiebenCorgie Is the world actually named `New\ World`? Because if it is not that putting the world's name in quotes and escaping the space won't work. For example:

```bash
$ echo New\ World    # Okay
New World
$ echo "New World"  # Okay
New World
$ echo "New\ World"  # Incorrect
New\ World
```

Even if that is what you meant, you might want to try renaming the file, just in case that is messing with stuff.

**Comment by SiebenCorgie** [comment]
I am sorry, this was actually the problem. However I created a new world called "Test" and tried to start it with 
`cargo run "Test"`
Then a window is opening, but closes after an error:
```
cargo run "Test" 
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/hematite Test`
Opening "/home/siebencorgie/.minecraft/versions/1.8.8/1.8.8.jar"...
File "/home/siebencorgie/.minecraft/versions/1.8.8/1.8.8.jar" contains 5597 files.
Extracted 3085 files.
{"Data": {"BorderSizeLerpTime": 0L, "rainTime": 173362i, "LastPlayed": 1486291659420L, "GameType": 0i, "DayTime": 82L, "initialized": 1b, "BorderSizeLerpTarget": 60000000.0, "generatorName": "default", "generatorVersion": 1i, "MapFeatures": 1b, "BorderWarningBlocks": 5.0, "Time": 82L, "version": 19133i, "Difficulty": 2b, "SpawnX": 281i, "SpawnZ": 43i, "Player": {"Motion": Double([0, -0.0784000015258789, 0]), "SelectedItemSlot": 0i, "HealF": 20.0f, "playerGameType": 0i, "Fire": -20s, "PortalCooldown": 0i, "XpLevel": 0i, "XpP": 0.0f, "UUIDLeast": -6378347348254606474L, "abilities": {"mayfly": 0b, "mayBuild": 1b, "walkSpeed": 0.1f, "flying": 0b, "instabuild": 0b, "flySpeed": 0.1f, "invulnerable": 0b}, "XpTotal": 0i, "Rotation": Float([-12.45, 19.35]), "UUIDMost": 5965671612684716656L, "Dimension": 0i, "EnderItems": Compound([]), "HurtByTimestamp": 0i, "FallDistance": 0.0f, "foodTickTimer": 0i, "Score": 0i, "Invulnerable": 0b, "Sleeping": 0b, "HurtTime": 0s, "Health": 20s, "Pos": Double([272.5, 68, 40.5]), "Attributes": Compound([{"Base": 20.0, "Name": "generic.maxHealth"}, {"Base": 0.0, "Name": "generic.knockbackResistance"}, {"Name": "generic.movementSpeed", "Base": 0.1}, {"Name": "generic.attackDamage", "Base": 1.0}]), "XpSeed": 0i, "foodSaturationLevel": 5.0f, "DeathTime": 0s, "Inventory": Compound([]), "foodExhaustionLevel": 0.4f, "AbsorptionAmount": 0.0f, "foodLevel": 20i, "SleepTimer": 0s, "OnGround": 1b, "Air": 300s}, "BorderWarningTime": 15.0, "DifficultyLocked": 0b, "BorderSafeZone": 5.0, "hardcore": 0b, "thundering": 0b, "BorderCenterX": 0.0, "BorderDamagePerBlock": 0.2, "LevelName": "Test", "GameRules": {"doMobSpawning": "true", "sendCommandFeedback": "true", "doFireTick": "true", "naturalRegeneration": "true", "doEntityDrops": "true", "commandBlockOutput": "true", "showDeathMessages": "true", "doDaylightCycle": "true", "doTileDrops": "true", "logAdminCommands": "true", "mobGriefing": "true", "reducedDebugInfo": "false", "keepInventory": "false", "doMobLoot": "true", "randomTickSpeed": "3"}, "SizeOnDisk": 0L, "raining": 0b, "clearWeatherTime": 0i, "BorderSize": 60000000.0, "allowCommands": 0b, "BorderCenterZ": 0.0, "thunderTime": 31107i, "SpawnY": 64i, "generatorOptions": "", "RandomSeed": -1052508251377029180L}}
ignoring 3 extra variants for stone#normal
ignoring 3 extra variants for grass#snowy=false
ignoring 3 extra variants for dirt#normal
ignoring 3 extra variants for bedrock#normal
ignoring 3 extra variants for sand#normal
ignoring 3 extra variants for red_sand#normal
ignoring 3 extra variants for tnt#normal
ignoring 31 extra frames in 'blocks/fire_layer_0'
ignoring 15 extra variants for netherrack#normal
ignoring 31 extra frames in 'blocks/portal'
ignoring 3 extra variants for waterlily#normal
Warning: model brewing_stand_empty uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_1 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_2 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_12 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_3 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_13 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_23 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_123 uses AO but has faces which are unsuitable
ignoring 31 extra frames in 'blocks/water_still'
Warning: model tripwire_hook uses AO but has faces which are unsuitable
Warning: model tripwire_hook uses AO but has faces which are unsuitable
Warning: model tripwire_hook uses AO but has faces which are unsuitable
Warning: model tripwire_hook uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached uses AO but has faces which are unsuitable
Warning: model tripwire_hook_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached_powered uses AO but has faces which are unsuitable
ignoring 3 extra frames in 'blocks/prismarine_rough'
ignoring 4 extra frames in 'blocks/sea_lantern'
thread 'main' panicked at 'Error InvalidValue creating buffer: Info { role: Vertex, usage: Data, bind: , size: 0, stride: 32 }', /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.13.0/src/factory.rs:162
```

The Error with RUST_BACKTRACE=1:
```
RUST_BACKTRACE=1 cargo run "Test"
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/hematite Test`
Opening "/home/siebencorgie/.minecraft/versions/1.8.8/1.8.8.jar"...
File "/home/siebencorgie/.minecraft/versions/1.8.8/1.8.8.jar" contains 5597 files.
Extracted 3085 files.
{"Data": {"rainTime": 173362i, "LevelName": "Test", "BorderSafeZone": 5.0, "generatorOptions": "", "raining": 0b, "BorderCenterX": 0.0, "hardcore": 0b, "BorderCenterZ": 0.0, "SizeOnDisk": 0L, "BorderSize": 60000000.0, "Player": {"foodTickTimer": 0i, "UUIDMost": 5965671612684716656L, "XpLevel": 0i, "Attributes": Compound([{"Base": 20.0, "Name": "generic.maxHealth"}, {"Name": "generic.knockbackResistance", "Base": 0.0}, {"Base": 0.1, "Name": "generic.movementSpeed"}, {"Base": 1.0, "Name": "generic.attackDamage"}]), "HealF": 20.0f, "Rotation": Float([-12.45, 19.35]), "AbsorptionAmount": 0.0f, "Fire": -20s, "XpP": 0.0f, "FallDistance": 0.0f, "Dimension": 0i, "Score": 0i, "EnderItems": Compound([]), "PortalCooldown": 0i, "Motion": Double([0, -0.0784000015258789, 0]), "XpSeed": 0i, "SleepTimer": 0s, "Pos": Double([272.5, 68, 40.5]), "Air": 300s, "SelectedItemSlot": 0i, "DeathTime": 0s, "Sleeping": 0b, "HurtTime": 0s, "foodSaturationLevel": 5.0f, "abilities": {"invulnerable": 0b, "mayfly": 0b, "flySpeed": 0.1f, "mayBuild": 1b, "walkSpeed": 0.1f, "flying": 0b, "instabuild": 0b}, "Inventory": Compound([]), "Invulnerable": 0b, "playerGameType": 0i, "OnGround": 1b, "XpTotal": 0i, "UUIDLeast": -6378347348254606474L, "foodLevel": 20i, "Health": 20s, "HurtByTimestamp": 0i, "foodExhaustionLevel": 0.4f}, "SpawnY": 64i, "MapFeatures": 1b, "allowCommands": 0b, "SpawnZ": 43i, "generatorVersion": 1i, "BorderSizeLerpTarget": 60000000.0, "Time": 82L, "DayTime": 82L, "initialized": 1b, "thunderTime": 31107i, "BorderWarningBlocks": 5.0, "generatorName": "default", "clearWeatherTime": 0i, "version": 19133i, "GameRules": {"doTileDrops": "true", "doDaylightCycle": "true", "showDeathMessages": "true", "randomTickSpeed": "3", "naturalRegeneration": "true", "doEntityDrops": "true", "mobGriefing": "true", "logAdminCommands": "true", "keepInventory": "false", "commandBlockOutput": "true", "doFireTick": "true", "doMobSpawning": "true", "doMobLoot": "true", "reducedDebugInfo": "false", "sendCommandFeedback": "true"}, "BorderSizeLerpTime": 0L, "BorderWarningTime": 15.0, "BorderDamagePerBlock": 0.2, "LastPlayed": 1486291659420L, "DifficultyLocked": 0b, "GameType": 0i, "SpawnX": 281i, "Difficulty": 2b, "thundering": 0b, "RandomSeed": -1052508251377029180L}}
ignoring 3 extra variants for stone#normal
ignoring 3 extra variants for grass#snowy=false
ignoring 3 extra variants for dirt#normal
ignoring 3 extra variants for bedrock#normal
ignoring 3 extra variants for sand#normal
ignoring 3 extra variants for red_sand#normal
ignoring 3 extra variants for tnt#normal
ignoring 31 extra frames in 'blocks/fire_layer_0'
ignoring 15 extra variants for netherrack#normal
ignoring 31 extra frames in 'blocks/portal'
ignoring 3 extra variants for waterlily#normal
Warning: model brewing_stand_empty uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_1 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_2 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_12 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_3 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_13 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_23 uses AO but has faces which are unsuitable
Warning: model brewing_stand_bottles_123 uses AO but has faces which are unsuitable
ignoring 31 extra frames in 'blocks/water_still'
Warning: model tripwire_hook uses AO but has faces which are unsuitable
Warning: model tripwire_hook uses AO but has faces which are unsuitable
Warning: model tripwire_hook uses AO but has faces which are unsuitable
Warning: model tripwire_hook uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached uses AO but has faces which are unsuitable
Warning: model tripwire_hook_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached_powered uses AO but has faces which are unsuitable
Warning: model tripwire_hook_attached_powered uses AO but has faces which are unsuitable
ignoring 3 extra frames in 'blocks/prismarine_rough'
ignoring 4 extra frames in 'blocks/sea_lantern'
thread 'main' panicked at 'Error InvalidValue creating buffer: Info { role: Vertex, usage: Data, bind: , size: 0, stride: 32 }', /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.13.0/src/factory.rs:162
stack backtrace:
   1:     0x55b5adef811a - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55b5adefcf6f - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x55b5adefb1d6 - std::panicking::default_hook::h5897799da33ece67
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x55b5adefb887 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x55b5adefb714 - std::panicking::begin_panic::hbb38be1379e09df0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x55b5adefb639 - std::panicking::begin_panic_fmt::h26713cea9bce3ab0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x55b5ad8a3af0 - gfx_device_gl::factory::Factory::init_buffer::h4444dceaa047506f
                        at /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.13.0/src/factory.rs:162
   8:     0x55b5ad8a465f - <gfx_device_gl::factory::Factory as gfx_core::factory::Factory<gfx_device_gl::Resources>>::create_buffer_immutable_raw::h92f3a577bad6d39b
                        at /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.13.0/src/factory.rs:326
   9:     0x55b5ad7f06e6 - gfx_core::factory::Factory::create_buffer_immutable::hfd88e29a87825976
                        at /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_core-0.6.0/src/factory.rs:200
  10:     0x55b5ad72f7bb - gfx::factory::FactoryExt::create_vertex_buffer::h20f1497ddd6ce533
                        at /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.14.0/src/factory.rs:110
  11:     0x55b5ad8253b4 - <hematite::shader::Renderer<R, F, C>>::new::h7fed6b6866019c8f
                        at /home/siebencorgie/Scripts/Rust/TutorialsNStuff/Piston/hematite/src/shader.rs:90
  12:     0x55b5ad827512 - hematite::main::h57298bcaf003982c
                        at /home/siebencorgie/Scripts/Rust/TutorialsNStuff/Piston/hematite/src/main.rs:159
  13:     0x55b5adf04a4a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  14:     0x55b5adefc2a5 - std::rt::lang_start::hd661476ce2fc2931
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  15:     0x55b5ad844202 - main
  16:     0x7f69dfd91290 - __libc_start_main
  17:     0x55b5ad6fc3c9 - _start
  18:                0x0 - <unknown>
```

I created the world with version 1.8.8 .

**Comment by userbq201** [comment]
+1

**Comment by userbq201** [comment]
```
Running `target/debug/hematite ./w1`
Opening "/home/userbq201/.minecraft/versions/1.8.8/1.8.8.jar"...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by rswalkden** [comment]
Working for me in a lubuntu 18.10 VM. I also left the save file in `~/.minecraft/saves/`.
